# THIS FILE IS MEANT TO BE AN EXAMPLE DOCKER COMPOSE FILE TO RUN THE BOT

version: '3.8'

services:
  bot:
    build: .
    image: in-house-queue
    # create a .env file in the root directory
    environment:
      # Discord bot token
      TOKEN: ${TOKEN}
    volumes:
      - inhouse-db:/app/db
    # if the bot fails it will attempt to restart, up to 5 times
    restart: on-failure

volumes:
  inhouse-db:
