# THIS FILE IS MEANT TO BE AN EXAMPLE DOCKER COMPOSE FILE TO RUN THE BOT

version: '3.8'

services:
  bot:
    build: .
    image: in-house-queue
    environment:
      TOKEN: ${TOKEN}
    volumes:
      - inhouse-db:/app/db
    restart: on-failure

volumes:
  inhouse-db:
