name: Run pytest tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        sudo yarn install --non-interactive
        sudo yarn global add prettier@1.17.0

    - name: Run Unit tests
      run: |
        make test
    
    - name: Codecov
        uses: codecov/codecov-action@v1.0.11
        with:
          file: ./coverage.xml
